### ISSUE TITLE
New interface not loading (white screen)

### ISSUE THREAD

**Issue by MrApe** [g4rb4g3/ABRPTransmitter#30]
With 3.1.7 the new (4.x) ABRP interface does not load. It only shows the ABRP logo and then a white screen. The old interface (3.xx) does work. 

![image](https://user-images.githubusercontent.com/98466/86239859-5a28b480-bba0-11ea-9c36-6a97bebb6445.jpg)

![image](https://user-images.githubusercontent.com/98466/86242464-0e2c3e80-bba5-11ea-9e90-92b594bc16e2.jpg)

![image](https://user-images.githubusercontent.com/98466/86242511-22703b80-bba5-11ea-837e-1845bf8fa3f8.jpg)

![image](https://user-images.githubusercontent.com/98466/86242581-34ea7500-bba5-11ea-8c69-ef31076a8c8e.jpg)

**Comment by g4rb4g3** [comment]
Hi,

new ABRP (4.x) isn't properly supported. I gave it a try and it worked until I switchted to driving mode.
So loading completed successfully, I could login and plan a route. Pressing the round blue arrow for driving mode switched over to a white screen.
I guess thats because our head unit misses something to properly show the 3D map in driving mode.
But this is nothing we can fix in ABRP Transmitter.

If it shows the white screen after loading try to clear cache and data of ABRP Transmitter. But still it will not work fully then. So for now only the classic (3.x) is an working option for us.
Maybe someday we will get a working ABRP app for our head unit....
https://forum.abetterrouteplanner.com/topic/1718-android-beta-apks/
